#!/usr/bin/env bash
# Regenerates the Swift and Kotlin UniFFI bindings for downstream consumers:
#   - Swift: this repo's SPM package (dist/swift, via build-xcframework.sh)
#   - Kotlin + Swift: the zmanager-mobile repo (checked-in generated files)
#
# The Kotlin/Swift source bindings are generated by generate-uniffi-bindings.sh.
# Set REGEN_KOTLIN_DIR / REGEN_SWIFT_DIR to redirect them elsewhere (CI uses
# this to write into crates/zmanager-ffi/bindings/), and ZM_SKIP_XCFRAMEWORK=1
# to skip the macOS-only SPM package build.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

MOBILE_ROOT="${ZMANAGER_MOBILE_ROOT:-$ROOT/../zmanager-mobile}"

if [[ "${ZM_SKIP_XCFRAMEWORK:-}" == "1" ]]; then
  echo "Skipping Swift package (xcframework) build (ZM_SKIP_XCFRAMEWORK=1)..."
else
  echo "Regenerating Swift package bindings for zmanager..."
  bash "$ROOT/scripts/build-xcframework.sh"
fi

if [[ -d "$MOBILE_ROOT" ]]; then
  echo "Regenerating mobile bindings in $MOBILE_ROOT..."
  REGEN_KOTLIN_DIR="${REGEN_KOTLIN_DIR:-$MOBILE_ROOT/android/app/src/main/java}" \
  REGEN_SWIFT_DIR="${REGEN_SWIFT_DIR:-$MOBILE_ROOT/ios/ZManagerMobile/ZManagerMobile/Bridge/Generated}" \
    bash "$ROOT/scripts/generate-uniffi-bindings.sh"
  echo "Mobile bindings regenerated: $MOBILE_ROOT/android/app/src/main/java/org/tzap/zmanager/mobile/bridge/generated/zmanager.kt, $MOBILE_ROOT/ios/ZManagerMobile/ZManagerMobile/Bridge/Generated"
else
  echo "Skipping mobile bindings: $MOBILE_ROOT not found (set ZMANAGER_MOBILE_ROOT to override)."
fi
